- OpenRPA.ExpressionEditor/EditorService.cs
- OpenRPA.ExpressionEditor/EditorUtil.cs
- OpenRPA.Java/JavaSelector.cs
- OpenRPA/Activities/TypeText.cs
- OpenRPA/Activities/TypeTextDesigner.xaml
- OpenRPA/Activities/TypeTextDesigner.xaml.cs
- OpenRPA/Activities/vKey.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
- OpenRPA/packages.config
- docs/index.md
Record TypeText and recording of keystrokes (and minimize on record/play)
> Record TypeText and recording of keystrokes (and minimize on record/play)

- OpenRPA.IE/OpenRPA.IE.csproj
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/Tracing.cs
- OpenRPA.Interfaces/win32/Zone.cs
- OpenRPA.Java/OpenRPA.Java.csproj
- OpenRPA.Java/Plugin.cs
- OpenRPA.Java/app.config
- OpenRPA.Java/javahook.cs
- OpenRPA.NativeMessagingHost/App.config
- OpenRPA.NativeMessagingHost/OpenRPA.NativeMessagingHost.csproj
- OpenRPA.Net/OpenRPA.Net.csproj
- OpenRPA.Windows/OpenRPA.Windows.csproj
- OpenRPA/App.config
- OpenRPA/MainWindow.xaml
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Project.cs
- OpenRPA/Views/WFDesigner.xaml
- OpenRPA/Workflow.cs
Fix a fix a few launching bugs.
> Fix a fix a few launching bugs

- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.Office/Activities/ReadRange.cs
- OpenRPA/Activities/InvokeOpenFlow.cs
- OpenRPA/Activities/InvokeOpenFlowDesigner.xaml
- OpenRPA/Activities/InvokeOpenFlowDesigner.xaml.cs
- OpenRPA/Activities/OpenApplicationDesigner.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Store/xmlInstanceStoreBase.cs
> improve InvokeOpenflow

- OpenRPA.Interfaces/UIElement.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA/Activities/InvokeOpenFlow.cs
- OpenRPA/MainWindow.xaml
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Store/xmlInstanceStoreBase.cs
- OpenRPA/Views/WFDesigner.xaml
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
- OpenRPA/WorkflowInstance.cs
- OpenRPA/WorkflowTrackingParticipant.cs
Add breakpoints and single stepping
> Add breakpoints and single stepping

- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Net/AppSettings.cs
- OpenRPA.Net/Config.cs
- OpenRPA.Net/OpenRPA.Net.csproj
- OpenRPA.Net/global.cs
- OpenRPA/MainWindow.xaml
- OpenRPA/MainWindow.xaml.cs
Add links to OpenFlow and NodeRED
> Add links to OpenFlow and NodeRED

- OpenRPA.Image/Plugin.cs
- OpenRPA/Activities/RemovePermissionDesigner.xaml
- OpenRPA/OpenRPA.csproj
Fix UI error in remove permissions.
Stop image plugin when clicking browsers
> Fix UI error in remove permissions.

- OpenRPA.Net/WebSocketClient.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/Project.cs
- OpenRPA/Views/KeyboardSeqWindow.xaml.cs
- OpenRPA/Views/PermissionsWindow.xaml.cs
- OpenRPA/Workflow.cs
Restrict cancel key to one key. Auto create new project for new users
> Restrict cancel key to one key. Auto create new project for new users

- OpenRPA.IE/IEElement.cs
- OpenRPA.Image/Activities/GetElementDesigner.xaml.cs
- OpenRPA.Image/Activities/GetImageDesigner.xaml.cs
- OpenRPA.Image/Activities/GetText.cs
- OpenRPA.Image/Activities/GetTextDesigner.xaml
- OpenRPA.Image/Activities/GetTextDesigner.xaml.cs
- OpenRPA.Image/ImageElement.cs
- OpenRPA.Image/getrectangle.cs
- OpenRPA.Image/ocr.cs
- OpenRPA.Interfaces/IElement.cs
- OpenRPA.Interfaces/Input/Input_OnInputStateChanged.cs
- OpenRPA.Interfaces/Overlay/OverlayWindow.cs
- OpenRPA.Interfaces/UIElement.cs
- OpenRPA.Java/JavaElement.cs
- OpenRPA.NM/NMElement.cs
- OpenRPA/OpenRPA.csproj
Add support for embedding GetImage in GetText
add word filter to gettext
fix overlay on windows 7
Show process limit when selecting.
> Improvements and bugfixes

- OpenRPA.Image/Activities/GetImageDesigner.xaml
- OpenRPA.Image/Activities/GetImageDesigner.xaml.cs
- OpenRPA.Image/Activities/GetText.cs
- OpenRPA.Image/ImageElement.cs
- OpenRPA.Image/getrectangle.cs
- OpenRPA.Image/ocr.cs
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/VersionHelper.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.Windows/WindowsSelector.cs
- OpenRPA.Windows/WindowsSelectorItem.cs
- OpenRPA.Windows/WindowsTreeElement.cs
- OpenRPA/Activities/ClickElement.cs
- OpenRPA/Activities/HighlightElement.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Settings.cs
Add CaseSensitive on GetText
Improve auto detecting parent in getimage  …
Fix weird bug with ControlType
> Improve auto detecting parent in getimage

- OpenRPA.Interfaces/CustomSelectEditor.cs
- OpenRPA.Interfaces/GenericTools.cs
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/packages.config
- OpenRPA.Office/Activities/NewMailItem.cs
- OpenRPA.Office/OpenRPA.Office.csproj
- OpenRPA/Activities/ShowNotification.cs
- OpenRPA/Activities/ShowNotificationDesigner.xaml
- OpenRPA/Activities/ShowNotificationDesigner.xaml.cs
- OpenRPA/App.xaml.cs
- OpenRPA/MainWindow.xaml
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/packages.config
> Add ShowNotification activity

- OpenRPA.Forms/Activities/Form.xaml.cs
Set form title based on form title or heading
> Set form title based on form title or heading

- OpenRPA.Forms/Activities/ShowNotification.cs
- OpenRPA.Interfaces/Selector/SelectorWindow.xaml.cs
- OpenRPA.NM/Activities/GetElement.cs
- OpenRPA.NM/Activities/GetElementDesigner.xaml.cs
- OpenRPA.NM/NMElement.cs
- OpenRPA.NM/NMSelector.cs
- OpenRPA.NM/NMSelectorItem.cs
- OpenRPA.NM/NMTreeElement.cs
- OpenRPA.NM/Plugin.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/Project.cs
- OpenRPA/Views/WFDesigner.xaml.cs
> Improve Native Messaging UI

- OpenRPA.Forms/Activities/Form.xaml
- OpenRPA.Forms/Activities/Form.xaml.cs
- OpenRPA.Image/Plugin.cs
- OpenRPA/Views/WFDesigner.xaml.cs
Load theme resources when showing a form to allow showing validation errors
> Load theme resources when showing a form

- OpenRPA/App.xaml
- OpenRPA/App.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/SingleInstanceMutex.cs
- OpenRPA/Views/LoginWindow.xaml
Allow only one instance of openrpa per user
> Allow only one instance of openrpa per user

- OpenRPA/Views/WFDesigner.xaml.cs
Quick fixing error when visual location not found failing workflow
> Quick fixing error when visual location not found failing workflow

- OpenRPA.Office/OpenRPA.Office.csproj
- OpenRPA.Office/packages.config
- OpenRPA.Script/Activities/Editor.xaml
- OpenRPA.Script/Activities/Editor.xaml.cs
- OpenRPA.Script/Activities/ErrorListener.cs
- OpenRPA.Script/Activities/ExecuteAHKScript.cs
- OpenRPA.Script/Activities/ExecuteAHKScriptDesigner.xaml.cs
- OpenRPA.Script/Activities/InvokeCode.cs
- OpenRPA.Script/Activities/InvokeCodeDesigner.xaml.cs
- OpenRPA.Script/OpenRPA.Script.csproj
- OpenRPA.Script/Resources/Autohotkey.xshd
- OpenRPA.Script/Resources/ICSharpCode.PythonBinding.Resources.Python.xshd
- OpenRPA.Script/packages.config
- OpenRPA/MainWindow.xaml.cs
Improve script editor and add more languages
> Improve script editor and add more languages

- OpenRPA.Script/Activities/InvokeCode.cs
A couple of bug fixes to InvokeCode
> A couple of bug fixes to InvokeCode

- OpenRPA.Updater/MainWindow.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/Project.cs
Panic update, since nuget searching is broken !!!
> Panic update, since nuget searching is broken !!!

- OpenRPA.Windows/Activities/GetElement.cs
- OpenRPA.Windows/PluginConfig.cs
- OpenRPA.Windows/WindowsSelector.cs
- OpenRPA.Windows/WindowsSelectorItem.cs
- OpenRPA/Project.cs
- OpenRPA/Workflow.cs
Test using UIThread in GetElement, can be reverted back by setting get_elements_in_different_thread true
> Test using UIThread in GetElement, can be reverted back by setting get_elements_in_different_thread true

- OpenRPA.Interfaces/IWebSocketClient.cs
- OpenRPA.Interfaces/IWorkflowInstance.cs
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/mq/RobotCommand.cs
- OpenRPA.Net/OpenRPA.Net.csproj
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.RDService/Program.cs
- OpenRPA.RDService/RobotUserSession.cs
- OpenRPA.RDService/unattendedclient.cs
- OpenRPA.RDServicePlugin/Views/RunPluginView.xaml
- OpenRPA.RDServicePlugin/Views/RunPluginView.xaml.cs
- OpenRPA.Updater/MainWindow.xaml.cs
- OpenRPA.Updater/OpenRPAPackageManager.cs
- OpenRPA/Activities/InvokeOpenRPA.cs
- OpenRPA/Activities/InvokeRemoteOpenRPA.cs
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
- OpenRPA/WorkflowInstance.cs
Add more aggressive minimizing, change timer type in rd service, add logout toggle
Add InvokeRemoteOpenRPA
Search without lookout for small/capital letters.
> Add more aggressive minimizing, Add InvokeRemoteOpenRPA, add Searching

- OpenRPA.Interfaces/AppSettings.cs
- OpenRPA.Interfaces/Config.cs
- OpenRPA.Interfaces/Extensions.cs
- OpenRPA.Interfaces/NativeMethods.cs
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/entity/apibase.cs
- OpenRPA.RDService/OpenRPA.RDService.csproj
- OpenRPA.RDService/PluginConfig.cs
- OpenRPA.RDService/Program.cs
- OpenRPA.RDService/Properties/launchSettings.json
- OpenRPA.RDService/RobotUserSession.cs
- OpenRPA.RDService/Tracing.cs
- OpenRPA.RDServicePlugin/OpenRPA.RDServicePlugin.csproj
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
Fix launch error in RDService and reconnect for RD Service, Add auto refresh to robot
> Fix launch error in RDService and reconnect for RD Service, Add auto refresh to robot

- OpenRPA.Interfaces/UIElement.cs
- OpenRPA.Windows/Activities/GetElement.cs
- OpenRPA.Windows/Activities/GetElementDesigner.xaml.cs
- OpenRPA.Windows/OpenRPA.Windows.csproj
- OpenRPA.Windows/Plugin.cs
- OpenRPA.Windows/WindowsSelector.cs
- OpenRPA/Activities/OpenApplication.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Workflow.cs
Improve open application, fix select error in nested windows elements
Fix Memory leak in auto reload, Fix issue when searching for ghost elements on Windows 7
> Improve open application / various bug fixes

- OpenRPA.IE/Plugin.cs
- OpenRPA.Interfaces/Config.cs
- OpenRPA.Interfaces/UIElement.cs
- OpenRPA.NM/Plugin.cs
- OpenRPA.Windows/Plugin.cs
- OpenRPA.Windows/WindowsSelectorItem.cs
- OpenRPA/Activities/OpenApplication.cs
- OpenRPA/Activities/OpenApplicationDesigner.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Workflow.cs
Add basic support for setting window position for NM and IE
improve window animation, and Add animation of both x,y,w,h too windows
Don't move with 0 values
Ensure parent in window cache
> Various improvements

- OpenRPA.AviRecorder/Resources/strings.de.resx
- OpenRPA.Elis.Rossum/Resources/strings.de.resx
- OpenRPA.FileWatcher/Resources/strings.de.resx
- OpenRPA.Forms/Resources/strings.de.resx
- OpenRPA.IE/Resources/strings.de.resx
- OpenRPA.Image/Resources/strings.de.resx
- OpenRPA.Interfaces/Resources/strings.de.resx
- OpenRPA.Java/Resources/strings.de.resx
- OpenRPA.NM/Resources/strings.de.resx
- OpenRPA.Office/Activities/ReadCell.cs
- OpenRPA.Office/Resources/strings.de.resx
- OpenRPA.OpenFlowDB/Resources/strings.de.resx
- OpenRPA.RDServicePlugin/Resources/strings.de.resx
- OpenRPA.Script/Resources/strings.de.resx
- OpenRPA.Updater/Resources/strings.de.resx
- OpenRPA.Utilities/Resources/strings.de.resx
- OpenRPA.Windows/Resources/strings.de.resx
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/ResFinder.cs
- OpenRPA/Resources/strings.de.resx
Add German translations, ( thank you Marcus von Goerne )
> Add German translations

- OpenRPA.Interfaces/GenericTools.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
Prompt for saving unsaved workflow on close
> Prompt for saving unsaved workflow on close

- OpenRPA.Interfaces/Extensions.cs
- OpenRPA.Interfaces/IWebSocketClient.cs
- OpenRPA.Interfaces/Input/InputDriver.cs
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Net/OpenRPA.Net.csproj
- OpenRPA.Net/QueryMessage.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.RDService/MyServiceControlInstaller.cs
- OpenRPA.RDService/OpenRPA.RDService.csproj
- OpenRPA.RDService/Program.cs
- OpenRPA.RDService/Tracing.cs
- OpenRPA.Windows/WindowsElementDetectorPlugin.cs
- OpenRPA.Windows/WindowsSelector.cs
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml.cs
- OpenRPA/App.xaml.cs
- OpenRPA/MainWindow.xaml
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Views/SigninWindow.xaml
- OpenRPA/Views/SigninWindow.xaml.cs
Swapping from IE to chrome for login screen. This will double the size of the robot. That annoys me, but there is just to many problems with the IE rendering of the federated login pages.
> Swap login screen from IE to chrome

- OpenRPA.Utilities/Extensions.cs
- OpenRPA.Utilities/OpenRPA.Utilities.csproj
- OpenRPA/MainWindow.xaml
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/strings.Designer.cs
- OpenRPA/Resources/strings.resx
- OpenRPA/Updater/Updates.cs
- README.md
- docs/index.md
Fix unicode characters for WriteCSV
Add version info to main menu, and change update check to offer download instead of using package manager
> Fix unicode characters for WriteCSV

- OpenRPA.IE/Activities/OpenURL.cs
- OpenRPA.IE/Browser.cs
- OpenRPA.IE/IEElement.cs
- OpenRPA.IE/IESelector.cs
- OpenRPA.IE/IESelectorItem.cs
- OpenRPA.IE/OpenRPA.IE.csproj
- OpenRPA.IE/Plugin.cs
- OpenRPA.IE/PluginConfig.cs
- OpenRPA.IE/Resources/strings.Designer.cs
- OpenRPA.IE/Resources/strings.resx
- OpenRPA.IE/Views/RecordPluginView.xaml
- OpenRPA.IE/Views/RecordPluginView.xaml.cs
- OpenRPA.IE/XPath.cs
- OpenRPA.IE/javascriptxml.js
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/Selector/SelectorWindow.xaml.cs
- OpenRPA.SetupProject/Product.wxs
- OpenRPA.SetupProject/compMain.wxs
- OpenRPA.Utilities/Activities/AddDataColumn.cs
- OpenRPA/App.xaml.cs
- OpenRPA/OpenRPA.csproj
- README.md
- docs/index.md
fix small issue with maxresult when highlighting
Improve OpenURL for IE
Add experimental support for XPath for IE, also doing recording
> Add experimental support for XPath for IE

- OpenRPA.IE/Activities/OpenURL.cs
- OpenRPA.IE/Browser.cs
- OpenRPA.IE/FakeSHDocVw.cs
- OpenRPA/App.xaml.cs
- OpenRPA/MainWindow.xaml.cs
Fix IE launching and language/locale not being set for all threads
> Fix IE launching and language/locale not being set for all threads

- OpenRPA.Java/OpenRPA.Java.csproj
- OpenRPA.Java/javahook.cs
- OpenRPA.Utilities/Activities/WriteCSVDesigner.xaml
- OpenRPA.Utilities/OpenRPA.Utilities.csproj
- OpenRPA.Utilities/Resources/strings.Designer.cs
- OpenRPA.Utilities/Resources/strings.resx
Fix JavaBridge initialization failure / Fix hint text in WriteCSV activity
> Fix JavaBridge initialization failure

- OpenRPA.NM/NMElement.cs
- OpenRPA.NM/OpenRPA.NM.csproj
- OpenRPA.NativeMessagingHost/OpenRPA.NativeMessagingHost.csproj
- OpenRPA.NativeMessagingHost/openrpautil.js
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Views/WFDesigner.xaml.cs
dup error in parseChromeString
Add ng-model as prefered selector
skadefro
Fix weak reference in oncancel
> small fixes

- OpenRPA.IE/Activities/GetElement.cs
- OpenRPA.IE/Browser.cs
- OpenRPA.IE/IESelector.cs
- OpenRPA.IE/OpenRPA.IE.csproj
- OpenRPA.IE/Plugin.cs
- OpenRPA.IE/XPath.cs
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/Selector/SelectorModel.cs
- OpenRPA.Interfaces/Selector/SelectorWindow.xaml
- OpenRPA/OpenRPA.csproj
Add support for nested getelement, when using xpath / better edit of json in selector
> Add support for nested getelement, when using xpath / better edit of json in selector

- OpenRPA.AviRecorder/Resources/strings.pt.resx
- OpenRPA.Elis.Rossum/Resources/strings.pt.resx
- OpenRPA.Forms/Resources/strings.pt.resx
- OpenRPA.IE/Resources/strings.pt.resx
- OpenRPA.Image/Resources/strings.pt.resx
- OpenRPA.Interfaces/Resources/strings.pt.resx
- OpenRPA.Java/Resources/strings.pt.resx
- OpenRPA.NM/Resources/strings.pt.resx
- OpenRPA.NativeMessagingHost/openrpautil.js
- OpenRPA.Office/Resources/strings.pt.resx
- OpenRPA.OpenFlowDB/Resources/strings.pt.resx
- OpenRPA.PDPlugin/Resources/strings.pt.resx
- OpenRPA.Script/Resources/strings.pt.resx
- OpenRPA.Utilities/Resources/strings.pt.resx
- OpenRPA.Windows/PluginConfig.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/strings.pt.resx
Improve portugues translation thanks too Rafael Homsi
> Improve portugues translation thanks too Rafael Homsi

- OpenRPA.NM/NMElement.cs
- OpenRPA.NativeMessagingHost/openrpautil.js
- OpenRPA.zreproj
- OpenRPA/CommandLineParser.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
- OpenRPA/WorkflowInstance.cs
Better error handling when called form commandline. Fix UI bug that could sometimes make workflow list as running when not running
> small bug fix

- OpenRPA.Interfaces/Config.cs
- OpenRPA.Interfaces/Extensions.cs
- OpenRPA.Interfaces/IDesigner.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.Utilities/Activities/JArrayToDataTable.cs
- OpenRPA/Activities/ForEachDataRow.cs
- OpenRPA/Activities/InvokeOpenFlow.cs
- OpenRPA/Activities/InvokeOpenFlowDesigner.xaml
- OpenRPA/Activities/InvokeOpenFlowDesigner.xaml.cs
- OpenRPA/Activities/InvokeOpenRPA.cs
- OpenRPA/Activities/InvokeOpenRPADesigner.xaml
- OpenRPA/Activities/InvokeOpenRPADesigner.xaml.cs
- OpenRPA/Activities/InvokeRemoteOpenRPA.cs
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml.cs
- OpenRPA/AgentWindow.xaml.cs
- OpenRPA/App.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/strings.Designer.cs
- OpenRPA/Resources/strings.resx
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
Add argument mapping dialog to Invoke Activities
Fix race condition when processing server queue messages
> Add argument mapping dialog to Invoke Activities and fix

- OpenRPA.IE/Browser.cs
- OpenRPA.IE/Plugin.cs
Remove unused code, mentioned in https://github.com/open-rpa/openrpa/issues/336
> Remove unused code

- OpenRPA.Interfaces/AsyncTaskCodeActivity.cs
- OpenRPA.Interfaces/Extensions.cs
- OpenRPA.Interfaces/UIElement.cs
- OpenRPA.Interfaces/entity/apibase.cs
- OpenRPA.Net/QueueMessage.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.Office/Activities/ReadRange.cs
- OpenRPA.OpenFlowDB/Activities/DataRowConverter.cs
- OpenRPA.OpenFlowDB/Activities/InsertOrUpdateOne.cs
- OpenRPA.OpenFlowDB/Activities/Query.cs
- OpenRPA.OpenFlowDB/Activities/UpdateFromDataTable.cs
- OpenRPA.OpenFlowDB/Activities/UpdateFromDataTableDesigner.xaml
- OpenRPA.OpenFlowDB/Activities/UpdateFromDataTableDesigner.xaml.cs
- OpenRPA.OpenFlowDB/OpenRPA.OpenFlowDB.csproj
- OpenRPA.OpenFlowDB/Resources/strings.Designer.cs
- OpenRPA.OpenFlowDB/Resources/strings.resx
- OpenRPA.SAP/SAPElement.cs
- OpenRPA.Utilities/Activities/ReadCSV.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
openflow: Fix uniqe parsing error in insert or update, add UpdateFromDataTable
> Fix uniqe parsing error in insert or update, add UpdateFromDataTable

- OpenRPA.NM/NMHook.cs
- OpenRPA.NM/OpenRPA.NM.csproj
- OpenRPA.NM/Plugin.cs
- OpenRPA.NativeMessagingHost/OpenRPA.NativeMessagingHost.csproj
- OpenRPA.NativeMessagingHost/background.js
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.Office/Activities/WriteRange.cs
- OpenRPA.OpenFlowDB/Activities/Query.cs
- OpenRPA.OpenFlowDB/Activities/UpdateFromDataTable.cs
- OpenRPA.Utilities/Activities/DeleteRow.cs
- OpenRPA.Utilities/Activities/DeleteRowDesigner.xaml
- OpenRPA.Utilities/Activities/DeleteRowDesigner.xaml.cs
- OpenRPA.Utilities/Activities/SetAllRowsState.cs
- OpenRPA.Utilities/Activities/SetAllRowsStateDesigner.xaml
- OpenRPA.Utilities/Activities/SetAllRowsStateDesigner.xaml.cs
- OpenRPA.Utilities/OpenRPA.Utilities.csproj
- OpenRPA.Utilities/Resources/strings.Designer.cs
- OpenRPA.Utilities/Resources/strings.resx
- OpenRPA/OpenRPA.csproj
nm: Fix addon after firefox update breaking things
utilities: add SetAllRowsState and DeleteRow
office: fix error when trying to save empty datatable
openflow: allow empty query
> Fix addon after firefox update breaking things

- OpenRPA.Image/Activities/GetColor.cs
- OpenRPA.Image/OpenRPA.Image.csproj
Make x and y arguments for GetColor 
https://github.com/open-rpa/openrpa/issues/314
> Make x and y arguments for GetColor

- OpenRPA.NM/NMElement.cs
- OpenRPA.NM/OpenRPA.NM.csproj
- OpenRPA.NativeMessagingHost/openrpautil.js
- OpenRPA.Script/Views/RecordPluginView.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
openrpa: Improve parsing arguments when called remotely
nm: Add Values to nmelement to support multi selects
> Improve parsing arguments when called remotely

- OpenRPA.Interfaces/WFHelper.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Views/WFDesigner.xaml.cs
Fix for https://github.com/open-rpa/openrpa/issues/350
> Fix default name / stop importing all default namespaces

- OpenRPA.NM/Download.cs
- OpenRPA.NM/OpenRPA.NM.csproj
- OpenRPA/OpenRPA.csproj
Fix for firefox https://github.com/open-rpa/openrpa/issues/358
> Fix Download message from firefox

- OpenRPA.NM/NMElement.cs
- OpenRPA.NM/OpenRPA.NM.csproj
- OpenRPA.Windows/Activities/GetElement.cs
- OpenRPA.Windows/OpenRPA.Windows.csproj
- OpenRPA/OpenRPA.csproj
Add WaitForVanish to NMElement
> Add WaitForVanish to NMElement

- OpenRPA.Script/Activities/InvokeCodeDesigner.xaml.cs
- OpenRPA.Script/OpenRPA.Script.csproj
- OpenRPA.Windows/Activities/GetElement.cs
- OpenRPA.Windows/WindowsSelectorItem.cs
- OpenRPA/OpenRPA.csproj
script.Add implementation variables to code designer
> script.Add implementation variables to code designer

- OpenRPA.Interfaces/Config.cs
- OpenRPA/OpenRPA.csproj
Fix login error (not saving byte array properly)
> Fix login error

- OpenRPA/Resources/strings.ja.resx
Want to Contribute Japanese Translation.
> Want to Contribute Japanese Translation

- OpenRPA.Database/Resources/strings.zh.resx
- OpenRPA.Elis.Rossum/Resources/strings.zh.resx
- OpenRPA.Forms/Resources/strings.zh.resx
- OpenRPA.MSSpeech/Resources/strings.zh.resx
- OpenRPA.Utilities/Activities/ReadPDF.cs
- OpenRPA.Utilities/OpenRPA.Utilities.csproj
- OpenRPA.Utilities/Resources/strings.zh.resx
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/strings.zh.resx
Test implementation of support for Arabic for readpdf
Update to Chinese translatio,, thanks to makehaha92
> Test implementation of support for Arabic for readpdf

- OpenRPA.Interfaces/Config.cs
- OpenRPA.Interfaces/IProject.cs
- OpenRPA.Interfaces/Plugins.cs
- OpenRPA.SetupProject/compUpdater.wxs
- OpenRPA/App.xaml.cs
- OpenRPA/Extensions.cs
- OpenRPA/MainWindow.xaml
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/NuGet/NuGetPackageManager.cs
- OpenRPA/NuGet/PackageSearchItem.cs
- OpenRPA/NuGet/PackageSourceWrapper.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Project.cs
- OpenRPA/Resources/strings.Designer.cs
- OpenRPA/Resources/strings.resx
- OpenRPA/RobotInstance.cs
- OpenRPA/Updater/OpenRPAPackageManager.cs
- OpenRPA/Views/BoolCollapsedConverter.cs
- OpenRPA/Views/BoolNotVisibilityConverter.cs
- OpenRPA/Views/BoolVisibilityConverter.cs
- OpenRPA/Views/OpenProject.xaml
- OpenRPA/Views/OpenProject.xaml.cs
- OpenRPA/Views/PackageManager.xaml
- OpenRPA/Views/PackageManager.xaml.cs
- OpenRPA/Views/wfToolbox.xaml.cs
- OpenRPA/Workflow.cs
> Re-add nuget support

- OpenRPA.IE/PluginConfig.cs
- OpenRPA.Interfaces/AsyncNativeActivity.cs
- OpenRPA.NM/Activities/GetElement.cs
- OpenRPA.NM/pipe/NamedPipeClient.cs
- OpenRPA.NativeMessagingHost/addon2/content.js
- OpenRPA.NativeMessagingHost/openrpautil.js
- OpenRPA.zreproj
- OpenRPA/OpenRPA.csproj
nm: Test rewriting GetElement as async, to support Cancel
nm: Fix javascript error in focus function
ie: make xpath default in IE
> improvements and test

- OpenRPA.Interfaces/IWorkflowInstance.cs
- OpenRPA.Script/Activities/Editor.xaml.cs
- OpenRPA.Script/Activities/InvokeCode.cs
- OpenRPA.Script/OpenRPA.Script.csproj
- OpenRPA.Script/Plugin.cs
- OpenRPA/Activities/InvokeOpenFlow.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/WorkflowInstance.cs
openrpa: Fix JArray parse error
script: Expose instance as variable
openrpa: Upgrade CefSharp.Wpf
> Fix JArray parse error / Expose instance as variable / Upgrade CefSharp.Wpf

- OpenRPA.NM/NMHook.cs
- OpenRPA.SetupProject/Product.wxs
- OpenRPA.SetupProject/compUpdater.wxs
- OpenRPA/MainWindow.xaml
- OpenRPA/Views/WFDesigner.xaml.cs
openrpa: auto add namespaces when adding or copy and pasting activities
openrpa: remove old, broken updater
> small updates

- OpenRPA.OpenFlowDB/Activities/AssignOpenFlow.cs
- OpenRPA.Windows/WindowsSelectorItem.cs
- OpenRPA/Activities/InvokeOpenFlow.cs
- OpenRPA/Activities/InvokeRemoteOpenRPA.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/ToolTipConvertor.cs
- OpenRPA/WorkflowTrackingParticipant.cs
> Minor fixes

- OpenRPA.Windows/OpenRPA.Windows.csproj
- OpenRPA.Windows/Plugin.cs
- OpenRPA.Windows/PluginConfig.cs
- OpenRPA.Windows/Resources/strings.Designer.cs
- OpenRPA.Windows/Resources/strings.resx
- OpenRPA.Windows/Views/RecordPluginView.xaml
- OpenRPA.Windows/Views/RecordPluginView.xaml.cs
- OpenRPA.Windows/WindowsSelector.cs
- OpenRPA.Windows/WindowsSelectorItem.cs
- OpenRPA/OpenRPA.csproj
add toggle for search_descendants
Fix config issue
skip FrameworkId in windows selector
> minor update

- OpenRPA.NM/NMHook.cs
- OpenRPA.NM/OpenRPA.NM.csproj
- OpenRPA/OpenRPA.csproj
nm: Launch edge using microsoft-edge: uri instead, fix connection test for edge/ff
> fix for edge and ff

- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.SAP/Activities/GetElementDesigner.xaml.cs
- OpenRPA.Windows/Activities/GetElementDesigner.xaml.cs
- OpenRPA.Windows/Views/WindowsClickDetectorView.xaml.cs
- OpenRPA.Windows/WindowsSelector.cs
- OpenRPA/OpenRPA.csproj
Windows: allow search_descendants any where in selector / Fix icon on highlight button
> allow search_descendants / Fix highlight icon

- OpenRPA.Interfaces/IWebSocketClient.cs
- OpenRPA.Interfaces/InArgumentStringConverter.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.PS/Queues/InvokeOpenflow.cs
- OpenRPA.PS/Queues/InvokeRemoteOpenRPA.cs
- OpenRPA.Utilities/Activities/DeleteAllRows.cs
- OpenRPA.Utilities/OpenRPA.Utilities.csproj
- OpenRPA/Activities/InvokeOpenFlow.cs
- OpenRPA/Activities/InvokeOpenFlowDesigner.xaml
- OpenRPA/Activities/InvokeOpenRPA.cs
- OpenRPA/Activities/InvokeOpenRPADesigner.xaml
- OpenRPA/Activities/InvokeRemoteOpenRPA.cs
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml
- OpenRPA/Activities/InvokeRemoteOpenRPADesigner.xaml.cs
- OpenRPA/AgentWindow.xaml.cs
- OpenRPA/Extensions.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
Utilities: Fix issue with DeleteAllRows
OpenRPA: Allow variables for Invoke OpenRPA
OpenRPA: add Expiration for invoke nodes
OpenRPA: Better handling of timeout messages
> A fix and a few improvements

- OpenRPA/OpenRPA.csproj
- OpenRPA/WorkflowInstance.cs
- OpenRPA/WorkflowTrackingParticipant.cs
Fix save state issue, fix otel time span issue
> Fix save state issue, fix otel time span issue

- OpenRPA.IE/Views/RecordPluginView.xaml.cs
- OpenRPA.Java/Views/RecordPluginView.xaml.cs
- OpenRPA.NM/Views/RecordPluginView.xaml.cs
- OpenRPA.RDServicePlugin/Views/RunPluginView.xaml.cs
- OpenRPA.Script/Views/RecordPluginView.xaml.cs
- OpenRPA.Windows/PluginConfig.cs
- OpenRPA.Windows/Views/RecordPluginView.xaml.cs
- OpenRPA.sln
- OpenRPA/OpenRPA.csproj
fix ui issue with recorder properties
> fix ui issue with recorder properties

- OpenRPA.Interfaces/Config.cs
- OpenRPA.Interfaces/OpenRPA.Interfaces.csproj
- OpenRPA.Interfaces/WFHelper.cs
- OpenRPA.Windows/WindowsElementDetectorPlugin.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
Better import handling and a few minor improvements
> Better import handling and a few minor improvements

- OpenRPA.IE/Activities/GetElement.cs
- OpenRPA.IE/Plugin.cs
- OpenRPA.Image/Activities/GetElement.cs
- OpenRPA.Image/Activities/GetImage.cs
- OpenRPA.Image/Matches.cs
- OpenRPA.Image/OpenRPA.Image.csproj
- OpenRPA.Image/Plugin.cs
- OpenRPA.Image/PluginConfig.cs
- OpenRPA.Image/Resources/strings.Designer.cs
- OpenRPA.Image/Resources/strings.resx
- OpenRPA.Image/Views/RecordPluginView.xaml
- OpenRPA.Image/Views/RecordPluginView.xaml.cs
- OpenRPA.Interfaces/IDesigner.cs
- OpenRPA.Interfaces/iMainWindow.cs
- OpenRPA.NM/Activities/GetElement.cs
- OpenRPA.Windows/Plugin.cs
- OpenRPA/AgentWindow.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
improve image recording, auto import namespaces on drop
> improve image recording, auto import namespaces on drop

- OpenRPA.Image/getrectangle.cs
- OpenRPA.Interfaces/Config.cs
- OpenRPA.Interfaces/mq/RobotCommand.cs
- OpenRPA.RDServicePlugin/Views/RunPluginView.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/WFDesigner.xaml.cs
Add support for killing robot workflow remotely
> Add support for killing robot workflow remotely

- OpenRPA.Image/Activities/PrintWindow.cs
- OpenRPA.Image/Activities/PrintWindowDesigner.xaml
- OpenRPA.Image/Activities/PrintWindowDesigner.xaml.cs
- OpenRPA.Image/OpenRPA.Image.csproj
- OpenRPA.Image/PrintCapture/PrintCaptureHelper.cs
- OpenRPA.Image/PrintCapture/Win32Consts.cs
- OpenRPA.Image/PrintCapture/Win32Funcs.cs
- OpenRPA.Image/PrintCapture/Win32Types.cs
- OpenRPA.Image/Resources/strings.Designer.cs
- OpenRPA.Image/Resources/strings.resx
Add a new PrintWindow activity to taking screenshot even when screen is locked by using PrintWindow API
> Add PrintWindow activity

- OpenRPA.Image/OpenRPA.Image.csproj
- OpenRPA.Interfaces/Plugins.cs
- OpenRPA.Script/OpenRPA.Script.csproj
- OpenRPA.Script/Plugin.cs
- OpenRPA.Script/PythonUtil/Setup.cs
- OpenRPA/OpenRPA.csproj
> python update

- OpenRPA/Activities/TypeText.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
Keyboard work around too FlaUI/FlaUI#295
> Keyboard work around

- OpenRPA.SetupProject/compMain.wxs
- OpenRPA.sln
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/WorkflowInstance.cs
- OpenRPA/WorkflowTrackingParticipant.cs
- dowinget.bat
- manifests/o/OpenRPAApS/OpenRPA/1.2.50.0/OpenRPAApS.OpenRPA.installer.yaml
- manifests/o/OpenRPAApS/OpenRPA/1.2.50.0/OpenRPAApS.OpenRPA.locale.en-US.yaml
- manifests/o/OpenRPAApS/OpenRPA/1.2.50.0/OpenRPAApS.OpenRPA.yaml
- sign.ps1
Remove OpenTelemetry stuff, going to move this to an extension later
> Remove OpenTelemetry stuff, going to move this to an extension later

- OpenRPA.Net/WebSocketClient.cs
- OpenRPA/OpenRPA.csproj
Fix, potential stall of processing of network messages
> Fix, potential stall of processing of network messages

- OpenRPA.NM/NMHook.cs
- OpenRPA.NM/Plugin.cs
- OpenRPA.NM/PluginConfig.cs
- OpenRPA/MainWindow.xaml
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/strings.Designer.cs
- OpenRPA/Resources/strings.resx
- OpenRPA/WorkflowInstance.cs
Add custom wait for tab timeout
> Add custom wait for tab timeout

- OpenRPA.Forms/Activities/InvokeForm.cs
- OpenRPA.Forms/Activities/InvokeFormDesigner.xaml
- OpenRPA.Forms/Activities/InvokeFormDesigner.xaml.cs
- OpenRPA.Forms/OpenRPA.Forms.csproj
- OpenRPA.Forms/Resources/strings.Designer.cs
- OpenRPA.Forms/Resources/strings.resx
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/WorkflowInstance.cs
Add variable mapper to invoke form, to support custom bindings
> Add variable mapper to invoke form, to support custom bindings

- OpenRPA.Interfaces/IWebSocketClient.cs
- OpenRPA.Net/InsertManyMessage.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.PS/Entities/Export-OpenRPAWorkflow.cs
- OpenRPA.PS/Entities/Load-XAMLImages.cs
- OpenRPA.PS/Entities/SetEntity.cs
- OpenRPA.PS/OpenRPA.PS.csproj
- OpenRPA/LocallyCached.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/OpenProject.xaml
- OpenRPA/Views/OpenProject.xaml.cs
Add drag and drop support. Fix isDirty property on remote update
Add support for loading images and exporting openrpa xaml workflows
Add support for insertmany to be used with AddEntity powershell cmdlet
> minor new features and a fix

- OpenRPA.Interfaces/Plugins.cs
- OpenRPA.NM/NMElement.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
and update error for innerHTML when page has changed.
> Fix issue loading nuget dlls

- OpenRPA.Interfaces/IWebSocketClient.cs
- OpenRPA.Net/Message.cs
- OpenRPA.Net/RegisterUserMessage.cs
- OpenRPA.Net/SocketCommand.cs
- OpenRPA.Net/SocketMessage.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA/AgentWindow.xaml.cs
- OpenRPA/Detector.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/OpenProject.xaml
Limit retry to specific commands, don't reset user object unless specifically calling signout, simplyfy retry code
> simplyfy retry code

- OpenRPA.Interfaces/Config.cs
- OpenRPA.Windows/WindowsSelectorItem.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/strings.Designer.cs
- OpenRPA/Resources/strings.resx
- OpenRPA/RobotInstance.cs
- OpenRPA/Store/OpenFlowInstanceStore.cs
- OpenRPA/Views/OpenProject.xaml
- OpenRPA/Views/OpenProject.xaml.cs
- OpenRPA/WorkflowInstance.cs
Option to toggle workflow state per workflow or globally using disable_instance_store
> Option to toggle workflow state per workflow or globally using disable_instance_store

- OpenRPA.Interfaces/IWorkitem.cs
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA.Net/WorkItemMessages.cs
- OpenRPA/Activities/Workitems/UpdateWorkitem.cs
- OpenRPA/Store/OpenFlowInstanceStore.cs
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/WorkitemQueue.cs
[Fix loading workflow instance after restart](https://github.com/open-rpa/openrpa/commit/6416afd75f4ad98a1f937bcbb746c00025272099)
[Add errortype](https://github.com/open-rpa/openrpa/commit/fe64aaaf68d6036193f4a170f2b4691a4700e6b7)
> Fix loading workflow instance after restart

- OpenRPA.Office/Activities/ReadCell.cs
- OpenRPA.Office/Activities/ReadRange.cs
- OpenRPA/RobotInstance.cs
- OpenRPA/WorkflowInstance.cs
Fix parsing dates in Read Cell
Fix parsing types when using headers=false in ReadRange
> Fix minor issue with Read Cell/Read Range

- OpenRPA.Interfaces/VT/IVTTerminal.cs
- OpenRPA.TerminalEmulator/Activities/GetTextAtDesigner.xaml
- OpenRPA.TerminalEmulator/Activities/GetTextAtDesigner.xaml.cs
- OpenRPA.TerminalEmulator/Activities/TerminalRecorder.xaml.cs
- OpenRPA.TerminalEmulator/Activities/termVB5250.cs
- OpenRPA.TerminalEmulator/Resources/strings.Designer.cs
- OpenRPA.TerminalEmulator/Resources/strings.resx
Improve "Get Text At" when using mouse to select field
> Add "Get text" test button to Get Text At.

- OpenRPA.NM/NMElement.cs
- OpenRPA.NativeMessagingHost/messagehandler.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
[Fix unicode character issue when sending to extension](https://github.com/open-rpa/openrpa/commit/e694690c018b5916c27e8103a5bfb78684a0493e)
[Don't send delete when removing missing items](https://github.com/open-rpa/openrpa/commit/f6b5e3bff4dd177621e58ccc8cd5bfc46873ce27)
[Return innerhtml if text is empty and has no children](https://github.com/open-rpa/openrpa/commit/acf2bcd03e5bb642af90858e6da038a034d8550f)
> minor improvements

- OpenRPA.Interfaces/UIElement.cs
I'm guessing one time is enough and the second section is a duplication mistake.
> Remove duplicate get Element ClassName section

- OpenRPA.AviRecorder/Resources/strings.zh_trad.resx
- OpenRPA.Database/Resources/strings.zh_trad.resx
- OpenRPA.Elis.Rossum/Resources/strings.zh_trad.resx
- OpenRPA.FileWatcher/Resources/strings.zh_trad.resx
- OpenRPA.Forms/Resources/strings.zh_trad.resx
- OpenRPA.IE/Resources/strings.zh_trad.resx
- OpenRPA.Image/Resources/strings.zh_trad.resx
- OpenRPA.Interfaces/Resources/strings.zh_trad.resx
- OpenRPA.Java/Resources/strings.zh_trad.resx
- OpenRPA.MSSpeech/Resources/strings.zh_trad.resx
- OpenRPA.NM/Resources/strings.zh_trad.resx
- OpenRPA.Office/Resources/strings.zh_trad.resx
- OpenRPA.OpenFlowDB/Resources/strings.zh_trad.resx
- OpenRPA.PDPlugin/Resources/strings.zh_trad.resx
- OpenRPA.RDServicePlugin/Resources/strings.zh_trad.resx
- OpenRPA.SAP/Resources/strings.zh_trad.resx
- OpenRPA.Script/Resources/strings.zh_trad.resx
- OpenRPA.Utilities/Resources/strings.zh_trad.resx
- OpenRPA.Windows/Resources/strings.zh_trad.resx
- OpenRPA/Resources/strings.zh_trad.resx
Hi Allan,
I'm indigos's colleague. (https://discourse.openiap.io/t/add-traditional-chinese-language/342)
We are from the IT department of The Taiwan-Mobile Co., Ltd.
There’s a new pull request that needs your approval.
Thank you in advance.
> Add Traditional Chinese language resource files

- OpenRPA.Forms/Resources/strings.zh_trad.resx
- OpenRPA.RDService/Client.cs
- OpenRPA.RDService/OpenRPA.RDService.csproj
- OpenRPA.RDService/PluginConfig.cs
- OpenRPA.RDService/Program.cs
- OpenRPA.RDService/RobotUserSession.cs
- OpenRPA.RDService/unattendedserver.cs
- OpenRPA.RDServicePlugin/OpenRPA.RDServicePlugin.csproj
- OpenRPA.RDServicePlugin/Views/RunPluginView.xaml.cs
- OpenRPA/OpenRPA.csproj
add better translations, add minor improvements to rd service
> add better translations, add minor improvements to rd service

- OpenRPA.Interfaces/IPCService/OpenRPAService.cs
- OpenRPA.Interfaces/IWorkflow.cs
- OpenRPA.Script/Activities/InvokeCode.cs
- OpenRPA.Script/Activities/ParseUtils.cs
- OpenRPA.Script/OpenRPA.Script.csproj
- OpenRPA/Activities/InvokeOpenRPA.cs
- OpenRPA/AgentWindow.xaml.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/RobotInstance.cs
- OpenRPA/Views/WFDesigner.xaml.cs
- OpenRPA/Workflow.cs
- OpenRPA/WorkflowInstance.cs
Fix issue where resume workflows would sometimes run workflows twice
Fix issue where chained workflows ( one workflow starting anther workflow ) would not get started in the right order when resumed after a restart.
Fix invoke code issue, where race condition could make invoke code fail, if trying to compile the same code twice.
Update invoke code to easily allow compiling for both python 3.7 and 3.11
> minor updates

- OpenRPA.Interfaces/BreakableLoop.cs
- OpenRPA.Interfaces/IWebSocketClient.cs
- OpenRPA.Net/OpenRPA.Net.csproj
- OpenRPA.Net/WebSocketClient.cs
- OpenRPA/MainWindow.xaml.cs
- OpenRPA/OpenRPA.csproj
- OpenRPA/RobotInstance.cs
Fix index/Total updates in BreakableLoop
Drop WebSockets package, will break windows xp, but remove a package
> Fix index/Total updates in BreakableLoop / Drop WebSockets package, will break windows xp, but remove a package

- OpenRPA.FileWatcher/Views/FileWatcherView.xaml.cs
- OpenRPA.Interfaces/Views/KeyboardDetectorView.xaml.cs
- OpenRPA.Java/Views/JavaClickDetectorView.xaml.cs
- OpenRPA.NM/NMHook.cs
- OpenRPA.NM/OpenRPA.NM.csproj
- OpenRPA.NM/Resources/strings.Designer.cs
- OpenRPA.NM/Resources/strings.resx
- OpenRPA.NM/URLDetectorPlugin.cs
- OpenRPA.NM/Views/URLDetectorView.xaml
- OpenRPA.NM/Views/URLDetectorView.xaml.cs
- OpenRPA.SetupProject/compMain.wxs
- OpenRPA.Windows/Views/WindowsClickDetectorView.xaml.cs
- OpenRPA/OpenRPA.csproj
> add url detector to nm

- OpenRPA.SetupProject/Product.wxs
- OpenRPA/OpenRPA.csproj
- OpenRPA/Views/PackageManager.xaml
Set script to optional package by default ( to avoid python crashes )
Remove update button on package manager ( has no effect if package was loaded )
> make scripts optioinal / Disable update button on package manager 

- OpenRPA.AviRecorder/Resources/strings.Designer.cs
- OpenRPA.AviRecorder/Resources/strings.resx
- OpenRPA.Database/Resources/strings.Designer.cs
- OpenRPA.Database/Resources/strings.resx
- OpenRPA.Elis.Rossum/Resources/strings.Designer.cs
- OpenRPA.Elis.Rossum/Resources/strings.resx
- OpenRPA.Forms/Resources/strings.Designer.cs
- OpenRPA.Forms/Resources/strings.resx
- OpenRPA.IE/Resources/strings.Designer.cs
- OpenRPA.IE/Resources/strings.resx
- OpenRPA.Image/Plugin.cs
- OpenRPA.Image/Resources/strings.Designer.cs
- OpenRPA.Image/Resources/strings.resx
- OpenRPA.Java/Resources/strings.Designer.cs
- OpenRPA.Java/Resources/strings.resx
- OpenRPA.NM/Resources/strings.Designer.cs
- OpenRPA.NM/Resources/strings.resx
- OpenRPA.sln
- OpenRPA/OpenRPA.csproj
- OpenRPA/Resources/strings.Designer.cs
- OpenRPA/Resources/strings.resx
- Update help links
- Stop adding process name to image.GetElement doing recording
- Update nm classes to public
> Update help links
